name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v

  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: viktorinox/icarus-verilog
      # env:
      #   NODE_ENV: development
      ports:
        - 80
      volumes:
        - my_docker_volume:/work
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
      - uses: actions/checkout@v3
      - name: Check for work dir
        run: ls /work
      - name: Check for mounted point
        run: pwd && ls src/
      - run: which iverilog
      - run: iverilog -g2012 src/11_operators_expressions/wildcard_equality.sv