name: Verilog Compile
on: [push]
jobs:

  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: viktorinox/icarus-verilog
      # env:
      #   NODE_ENV: development
      ports:
        - 80
      volumes:
        - my_docker_volume:/work
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
      - uses: actions/checkout@v3
      - name: Check for work dir
        run: ls /work
      - name: Check for mounted point
        run: pwd && ls src/
      - run: which iverilog
      - run: iverilog -g2012 src/11_operators_expressions/wildcard_equality.sv

  eda-playground-job:
    runs-on: ubuntu-latest
    environment: test
    # container:
    #   image: selenium/standalone-chrome
    #   # env:
    #   #   NODE_ENV: development
    #   ports:
    #     - 80
    #   volumes:
    #     - my_docker_volume:/work
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt update
      - run: sudo apt install wget unzip python3-pip -y
      - run: cd /home/
      - run: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - run: sudo dpkg -i google-chrome-stable_current_amd64.deb
      - run: sudo apt-get install -f -y
      - run: sudo dpkg -i google-chrome-stable_current_amd64.deb
      - run: google-chrome --version
      - run: wget https://chromedriver.storage.googleapis.com/108.0.5359.71/chromedriver_linux64.zip
      - run: unzip ./chromedriver_linux64.zip
      - run: sudo mv chromedriver /usr/bin/
      - run: sudo chmod +x /usr/bin/chromedriver
      - run: pip install selenium==3.14.1
      - run: chromedriver --url-base=/wd/hub --whitelisted-ips= &
      - env:
          EDA_LOGIN: ${{ secrets.EDA_LOGIN }}
          EDA_TOKEN: ${{ secrets.EDA_TOKEN }}
          EDA_HEADLESS: 1
        run: python3 run.py
      - run: ls
      - run: mkdir -p results && unzip result.zip -d results/
      - run: cat results/xrun.log

